
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: front
spec:
  selector:
    matchLabels:
      app: front
  replicas: 1 
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front
        imagePullPolicy: Always
        image: gcr.io/useful-patrol-241412/chack-yoda-front:v1
        ports:
        - containerPort: 80
      