
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: "mongo"
  selector:
    matchLabels:
      app: mongo
  replicas: 1  
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers: 
      - name: mongo
        image: gcr.io/useful-patrol-241412/mongo:v1
        ports:
        - containerPort: 27017
        lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "mongorestore --db ChackYoda ChackYoda"]
      